plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "framer-motion@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/react-utils@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/portal@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/toast@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/transition@*":
    dependencies:
      framer-motion: "*"
  "@chakra-ui/checkbox@*":
    dependencies:
      framer-motion: "*"
  "@chakra-ui/media-query@*":
    dependencies:
      "@chakra-ui/theme": "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      "react": "*"
  "@chakra-ui/theme-tools@*":
    dependencies:
      "@chakra-ui/system": "*"
